// Code generated by k8s-api-codegen. DO NOT EDIT.

// Package v1 contains the types for network.prismacloud.io/v1
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen=package
// +k8s:defaulter-gen=TypeMeta
// +k8s:conversion-gen=go.aporeto.io/gaia-k8s/pkg/apis/networkprismacloudio/v1
// +groupName=network.prismacloud.io
package v1
